name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v2
      
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run all registered code quality checks (Lint, Checkstyle, tests and JaCoCo)
      run: ./gradlew luch:check

    - name: Upload code coverage reports to codecov
      uses: codecov/codecov-action@v1
